stages:
  - publish

.publish:
  stage: publish
  image: node:20-alpine
  resource_group: $PACKAGE
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest --activate
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm i
    - cd packages/$PACKAGE
    - echo "@outloud:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/" >> .npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - pnpm publish

publish:nuxt:
  extends: .publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^nuxt\@.*$/
  variables:
    PACKAGE: nuxt

publish:adonisjs:
  extends: .publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^adonisjs\@.*$/
  variables:
    PACKAGE: adonisjs

publish:typescript:
  extends: .publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^typescript\@.*$/
  variables:
    PACKAGE: typescript
